src/Entity/Franchise.php
<?php

namespace App\Entity;

use App\Repository\FranchiseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FranchiseRepository::class)]
class Franchise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?bool $sell_drink = null;

    #[ORM\OneToMany(mappedBy: 'franchise', targetEntity: Structure::class)]
    private Collection $structure;

    #[ORM\Column]
    private ?bool $mailing = null;

    #[ORM\Column]
    private ?bool $promotion_salle = null;

    #[ORM\Column]
    private ?bool $team_planning = null;

    #[ORM\Column]
    private ?bool $active = null;

    #[ORM\Column(length: 255)]
    private ?string $mail = null;

    public function __construct()
    {
        $this->structure = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function isSellDrink(): ?bool
    {
        return $this->sell_drink;
    }

    public function setSellDrink(bool $sell_drink): self
    {
        $this->sell_drink = $sell_drink;

        return $this;
    }

    /**
     * @return Collection<int, Structure>
     */
    public function getStructure(): Collection
    {
        return $this->structure;
    }

    public function addStructure(Structure $structure): self
    {
        if (!$this->structure->contains($structure)) {
            $this->structure->add($structure);
            $structure->setFranchise($this);
        }

        return $this;
    }

    public function removeStructure(Structure $structure): self
    {
        if ($this->structure->removeElement($structure)) {
            // set the owning side to null (unless already changed)
            if ($structure->getFranchise() === $this) {
                $structure->setFranchise(null);
            }
        }

        return $this;
    }

    public function isMailing(): ?bool
    {
        return $this->mailing;
    }

    public function setMailing(bool $mailing): self
    {
        $this->mailing = $mailing;

        return $this;
    }

    public function isPromotionSalle(): ?bool
    {
        return $this->promotion_salle;
    }

    public function setPromotionSalle(bool $promotion_salle): self
    {
        $this->promotion_salle = $promotion_salle;

        return $this;
    }

    public function isTeamPlanning(): ?bool
    {
        return $this->team_planning;
    }

    public function setTeamPlanning(bool $team_planning): self
    {
        $this->team_planning = $team_planning;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }
}

src/Controller/AdminFranchiseController.php
<?php

namespace App\Controller;

use App\Entity\Franchise;
use App\Form\FranchiseType;
use App\Entity\FranchiseSearch;
use App\Form\FranchiseSearchType;
use App\Repository\FranchiseRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;

#[Route('/admin/franchise')]
class AdminFranchiseController extends AbstractController
{
    #[Route('/', name: 'app_admin_franchise_index', methods: ['GET'])]
    public function index(FranchiseRepository $franchiseRepository, Request $request): Response
    {
        $search = new FranchiseSearch();
        $form = $this->createForm(FranchiseSearchType::class, $search);
        $form->handleRequest($request);

        return $this->render('admin_franchise/index.html.twig', [
            'franchises' => $franchiseRepository->findAllVisible($search),
            'form' => $form->createView()
        ]);
    }

    #[Route('/new', name: 'app_admin_franchise_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FranchiseRepository $franchiseRepository, MailerInterface $mailer): Response
    {
        $franchise = new Franchise();
        $form = $this->createForm(FranchiseType::class, $franchise);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $franchiseRepository->add($franchise, true);

            $email = (new Email())
            ->from('Stay@Fit.com')
            ->to($franchise->getMail())
            //->cc('cc@example.com')
            //->bcc('bcc@example.com')
            //->replyTo('fabien@example.com')
            //->priority(Email::PRIORITY_HIGH)
            ->subject('Votre Franchise a été créer')
            ->html('Votre franchise '. $franchise->getName(). ' a été créer');

        $mailer->send($email);

            return $this->redirectToRoute('app_admin_franchise_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_franchise/new.html.twig', [
            'franchise' => $franchise,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_franchise_show', methods: ['GET'])]
    public function show(Franchise $franchise): Response
    {
        return $this->render('admin_franchise/show.html.twig', [
            'franchise' => $franchise,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_franchise_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Franchise $franchise, FranchiseRepository $franchiseRepository, MailerInterface $mailer): Response
    {
        $form = $this->createForm(FranchiseType::class, $franchise);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $franchiseRepository->add($franchise, true);

            $email = (new Email())
            ->from('Stay@Fit.com')
            ->to($franchise->getMail())
            //->cc('cc@example.com')
            //->bcc('bcc@example.com')
            //->replyTo('fabien@example.com')
            //->priority(Email::PRIORITY_HIGH)
            ->subject('Des modification ont été effectué')
            ->html('Les permissions globales de votre franchise ont été modifié');

        $mailer->send($email);

            return $this->redirectToRoute('app_admin_franchise_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_franchise/edit.html.twig', [
            'franchise' => $franchise,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_franchise_delete', methods: ['POST'])]
    public function delete(Request $request, Franchise $franchise, FranchiseRepository $franchiseRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$franchise->getId(), $request->request->get('_token'))) {
            $franchiseRepository->remove($franchise, true);
        }

        return $this->redirectToRoute('app_admin_franchise_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_franchise/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_franchise_delete', {'id': franchise.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ franchise.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/admin_franchise/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/admin_franchise/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la franchise{% endblock %}

{% block body %}
    <h1 class="ms-3">Modifier la franchise</h1>
<div class="container-fluid">

    {{ form_start(form) }}
    {{ form_widget(form) }}
        <div class="d-flex justify-content-evenly">
        <button class="btn btn-primary">{{ button_label|default('Mettre à jour') }}</button>
        <a class="btn btn-info" href="{{ path('app_admin_franchise_index') }}">Retour</a>         
    {{ form_end(form) }}
    {{ include('admin_franchise/_delete_form.html.twig') }}
    </div>
</div>




{% endblock %}

templates/admin_franchise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des franchises{% endblock %}

{% block body %}
    <h1 class="ms-3">Liste des franchises</h1>
	<div class="container-fluid" style="width: 300px">
			{{ form_start(form) }}
			   {{ form_row(form.name) }}
			   {{ form_row(form.options) }}
			   <a class="btn btn-info" aria-current="page" href="{{ path('app_admin_franchise_index') }}">Réinitialiser</a>
			{{ form_end(form) }}
	</div>		

<div class="d-flex justify-content-center flex-wrap">

{% for franchise in franchises %}
	{% if app.user %}
	{% if 'ROLE_FRANCHISE' in app.user.roles and app.user.email == franchise.mail %}
	<div class="card me-3 mt-5" style="width: 18rem;">
		<div class="card-body">
			<p class="card-text">{{ franchise.active ? 'Franchise on' : 'Franchise off' }}</p>
			<h5 class="card-title">{{ franchise.name }}</h5>
			<h6 class="card-subtitle mb-2 text-muted">Permission globale</h6>
			<p class="card-text">{{ franchise.sellDrink ? 'Vente de boissons activé' : 'Vente de boissons désactivé' }}</p>
			<p class="card-text">{{ franchise.mailing ? 'Faire son mailing activé' : 'Faire son mainling désactivé' }}</p>
			<p class="card-text">{{ franchise.promotionSalle ? 'Promption de la salle activé' : 'Promotion de la salle désactivé' }}</p>
			<p class="card-text">{{ franchise.teamPlanning ? 'Gérer le planning d\'équipe activé' : 'Gérer le planning d\'équipe désactivé' }}</p>
			<div class="d-flex justify-content-between">
			<a class="btn btn-primary" href="{{ path('app_admin_franchise_show', {'id': franchise.id}) }}">Voir les structures</a>
			</div>
		</div>
	</div>
	{% endif %}
	{% endif %}

	{% if app.user %}
	{% if 'ROLE_ADMIN' in app.user.roles %}

		<div class="card me-3 mt-5" style="width: 18rem;">
		<div class="card-body">
			<p class="card-text">{{ franchise.active ? 'Franchise on' : 'Franchise off' }}</p>
			<h5 class="card-title">{{ franchise.name }}</h5>
			<h6 class="card-subtitle mb-2 text-muted">Permission globale</h6>
			<p class="card-text">{{ franchise.sellDrink ? 'Vente de boissons activé' : 'Vente de boissons désactivé' }}</p>
			<p class="card-text">{{ franchise.mailing ? 'Faire son mailing activé' : 'Faire son mainling désactivé' }}</p>
			<p class="card-text">{{ franchise.promotionSalle ? 'Promption de la salle activé' : 'Promotion de la salle désactivé' }}</p>
			<p class="card-text">{{ franchise.teamPlanning ? 'Gérer le planning d\'équipe activé' : 'Gérer le planning d\'équipe désactivé' }}</p>
			<div class="d-flex justify-content-between">
			<a class="btn btn-primary" href="{{ path('app_admin_franchise_show', {'id': franchise.id}) }}">Voir les structures</a>
			<a class="btn btn-info" href="{{ path('app_admin_franchise_edit', {'id': franchise.id}) }}">Modifier</a>
			</div>
		</div>
	</div>

	{% endif %}
	{% endif %}
{% endfor %}
</div>

{% if app.user %}
{% if 'ROLE_ADMIN' in app.user.roles %}
<a class="btn btn-primary ms-2 mt-4 mb-3" href="{{ path('app_admin_franchise_new') }}">Ajouter une franchise</a>
{% endif %}
{% endif %}

{% endblock %}

templates/admin_franchise/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter uen franchise{% endblock %}

{% block body %}
    <h1 class="ms-3">Ajouter une franchise</h1>
<div class="container-fluid">

	{{ form_start(form) }}
	{{ form_widget(form) }}
	<button class="btn btn-primary">{{ button_label|default('Ajouter') }}</button>
	<a class="btn btn-info" href="{{ path('app_admin_franchise_index') }}">Retour</a>
	{{ form_end(form) }}
</div>

{% endblock %}

templates/admin_franchise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des structures{% endblock %}

{% block body %}
    <h1 class="ms-3">Liste des structures</h1>
        <div class="d-flex justify-content-center flex-wrap">
     {% for structure in franchise.structure %}
     <div class="card mt-4 me-4" style="width: 18rem;">
        <div class="card-body">
        	<p class="card-text">{{ structure.active ? 'Structure on' : 'Structure off' }}</p>
            <h5 class="card-title">{{ structure.name }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ structure.address }}</h6>
            <p class="card-text">{{ franchise.sellDrink ? 'Vente de boissons activé' : 'Vente de boissons désactivé' }}</p>
            <p class="card-text">{{ franchise.mailing ? 'Faire son mailing activé' : 'Faire son mainling désactivé' }}</p>
            <p class="card-text">{{ franchise.promotionSalle ? 'Promption de la salle activé' : 'Promotion de la salle désactivé' }}</p>
            <p class="card-text">{{ franchise.teamPlanning ? 'Gérer le planning d\'équipe activé' : 'Gérer le planning d\'équipe désactivé' }}</p>
            {% if app.user %}
	        {% if 'ROLE_ADMIN' in app.user.roles %}
            <a class="btn btn-info" href="{{ path('app_admin_structure_edit', {'id': structure.id}) }}">Modifier</a>
            {% endif %}
	        {% endif %}
        </div>
        </div>
            {% endfor %}
            </div>
    {% if app.user %}
	{% if 'ROLE_ADMIN' in app.user.roles %}
    <a class="btn btn-primary mt-4 me-2 ms-2 mb-3" href="{{ path('app_admin_structure_new', {'id': franchise.id}) }}">Ajouter une structure</a>
    {% endif %}
	{% endif %}
    <a class="btn btn-info ms-3 mt-4 mb-3" href="{{ path('app_admin_franchise_index') }}">Retour</a>
{% endblock %}